ALTER TABLE organizations ADD COLUMN IF NOT EXISTS has_payment_method BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS trial_end_date TIMESTAMPTZ;
ALTER TABLE daemons ADD COLUMN IF NOT EXISTS standby BOOLEAN NOT NULL DEFAULT false;
